name: Update AdGuard SRS

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Install sing-box
        run: |
          curl -fsSL https://sing-box.app/install.sh | sh  -s -- --version 1.12.17

      - name: Download AdGuard filter.txt
        run: |
          curl -fsSL -o filter.txt https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt

      - name: Convert to SRS
        id: convert
        run: |
          output=$(sing-box rule-set convert --type adguard --output adguard-filter-list.srs filter.txt 2>&1)
          echo "$output"
          ratio=$(echo "$output" | grep -oE '[0-9]+/[0-9]+')
          echo "ratio=$ratio" >> "$GITHUB_OUTPUT"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.run_number }}
          name: Release ${{ github.run_number }}
          files: |
            adguard-filter-list.srs
          body: |
            Parsed rules: ${{ steps.convert.outputs.ratio }}
            Automatic file publishing:
            - adguard-filter-list.srs: Sing-box rule_set format
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
